service: aws-python-flask-dynamodb-api-project

frameworkVersion: '3'

custom:
  tableName: 'users-table-${self:provider.stage}'
  pythonRequirements:
    dockerizePip: true
  wsgi:
    app: src/app.app

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  profile: martz-personal
  stage: dev
  timeout: 10
  memorySize: 128
  deploymentBucket:
    name: ${self:service}-${opt:stage, self:provider.stage}-deployment-bucket
    serverSideEncryption: AES256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    REGION_NAME: ${self:provider.region}
    IS_OFFLINE: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-deployment-bucket

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
